B#src 5453 fix reset bug
shadow-robot/polhemus_ros_driver pull request #20
Opened 2020-11-25 11:53 UTC by giusebar

General refactoring, fix bug with reset, fix calibration boresight bug

2020-11-25 13:18 UTC, mikramarc requested changes

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +    tf2::Quaternion current_quaternion;
can we name it more explanatory? also maybe remove current? to me it suggests there is some previous.. like station_quaternion? not adamant about this one tho

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +    current_roll = (current_roll * 180) / PI;
station_roll?

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +    if (name == "viper")
bleh

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +    if (retval == RETURN_ERROR)
reverse order please, its c++

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +      return -1;
no need to break if u return

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +  for (int station_id = 0; station_id < station_count; ++station_id)
this is almost all duplicated code. Should we wrap in a method?

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
>    if (system(cmd.c_str()))
does it return true when it fails? sup with dat

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
> +void reset_and_release_polhemus_device(Polhemus *device, libusb_device_handle *g_usbhnd, vp_usbdevinfo g_usbinfo)
should be two methods

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
>      if (retval == RETURN_ERROR)
reverse order

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
> +  bool ready_to_start = true;
do we need this? shoudnt we justr immediately terminate if its not ready?

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
>    if (retval == RETURN_ERROR)
reverse

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
> +    return 0;
all returns should be -1, 0 code means success

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
> +    return 0;
or some other code, just not zero

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/viper.cpp
>  tf2::Quaternion Viper::get_quaternion(int index)
get quaternion of what? index of what?

2020-11-25 13:18 UTC, mikramarc commented on src/polhemus_ros_driver/viper.cpp
> +    throw "Could not retrieve current sensor orientation, empty sensor frame!";
please throw known exception, not just message

2020-11-27 13:49 UTC, giusebar commented on src/polhemus_ros_driver/polhemus.cpp
> +    if (name == "viper")
lol

2020-11-27 13:51 UTC, giusebar commented on src/polhemus_ros_driver/polhemus.cpp
> +  for (int station_id = 0; station_id < station_count; ++station_id)
mm not really, it's quite different, in one we set and in one we get the params. mainly the loop is similar, but there are quite a lot of different things going on

2020-11-27 13:52 UTC, giusebar commented on src/polhemus_ros_driver/polhemus.cpp
>    if (system(cmd.c_str()))
ye, weird ? !

2020-11-27 16:12 UTC, mikramarc requested changes

2020-11-27 16:12 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +      throw error;
Just throw; is enough i think

2020-11-27 16:12 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +      ROS_WARN("[POLHEMUS] No previous calibration data available, please calibrate before proceeding!!!");
wow, three exclamation marks, very serious

2020-11-27 16:12 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
> +void release_polhemus_device(Polhemus *device, libusb_device_handle *g_usbhnd, vp_usbdevinfo g_usbinfo)
why have this in one method? Just do release device with only device arg, and release usb separately?

2020-11-27 16:12 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
>      if (retval == RETURN_ERROR)
DO IT

2020-11-27 16:44 UTC, mikramarc requested changes

2020-11-27 16:44 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +        ROS_ERROR("[POLHEMUS] Caliration - error getting complete frame in required time.");
```suggestion
        ROS_ERROR("[POLHEMUS] Calibration - error getting complete frame in required time.");
```

2020-11-27 16:44 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +      retval = 4;
great code

2020-11-30 10:51 UTC, mikramarc approved these changes

2020-11-30 10:59 UTC, ToivoS approved these changes

2020-11-30 11:01 UTC, merged