Fix bimanual calibration
shadow-robot/polhemus_ros_driver pull request #21
Opened 2020-12-10 16:02 UTC by giusebar

Fix bimanual calibration and refactor calibration functions

2020-12-10 16:23 UTC, ToivoS approved these changes

2020-12-11 14:49 UTC, mikramarc requested changes

2020-12-11 14:49 UTC, mikramarc commented on src/polhemus_ros_driver/polhemus.cpp
> +  if (hands == "both")
passing here by string seems messy and unnecessary. Maybe just number of hands passed? That way we dont need to handle string and no need for if

2020-12-16 11:26 UTC, mikramarc approved these changes

2020-12-16 11:26 UTC, merged