Creating new glove calibration method
shadow-robot/polhemus_ros_driver pull request #38
Opened 2022-08-03 08:32 UTC by maxzieba

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropriate.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [X] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-08-10 09:20 UTC, bdenoun requested changes
Need to change structure of the classes as plenty of methods should be refactored

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +#!/usr/bin/env python3
Could we find another name for the file? ..._calibration_as.py? What does that mean?

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +from visualization_msgs.msg import *
no wildcard imports

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +import numpy as np
import numpy more than once

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +from interactive_markers.interactive_marker_server import *
remove wildcards in all your imports

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        self.id = DataMarker._id = DataMarker._id + 1
Can you explain this?

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        if isinstance(color, str):
Creating an enum with colors might make more sense here

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        self._fingers = ('ff', 'mf', 'rf', 'lf')
same comment as other PR, should be outside of the class

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        if not self._hand_side == "lh":
Wait, what? Why not using self._hand_side != "lh"?

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +            self._im_server = InteractiveMarkerServer(f"knuckle_position_markers")
rename im-server as it is not meaningful, it could stand for image for instance

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +            self._as = actionlib.SimpleActionServer(f"/calibration_action_server", CalibrateAction,
as is not meaningful either, please change

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        for key, value in {"polhemus_base_0": "rh", "polhemus_base_1": "lh"}.items():
Same as other PR, please make the dictionary a constant that can be changed outside of the class

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +                station_name = f"polhemus_station_{i + 8*self._index + 1}"
A small comment about why do you have 8 would help maintanability

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +    def _process_feedback(self, feedback):
Defining a class method that does nothing makes me raise some questions about what you are trying to do here.

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        size_ratio = 0.2
We might want to play with this value alter on, so please make it something configurable

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        if isinstance(color, str):
An enum makes sense

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        def _create_control(quaternion, name):
Is there any specific reason for creating this method inside another one?

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        rate = rospy.Rate(100)
Might want to play with this value, so please make it configurable

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +                    (pos, _) = self._listener.lookupTransform(self._base, polhemus_tf_name,
you don't need brackets here. You could just have pos,_ = ...

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +    def _sphere_fit(self, data):
This method should be static or even better should be outside of the class

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        A = np.zeros((len(x), 4))
please rename most of the variables in this method

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +    def _map_range(self, value, in_min, in_max, out_min, out_max):
same here, nothing related to the object or class in here

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +    def calculate_distance(self, point1, point2):
should be static or outside of the class

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/publish_static_knuckle_tf.py
> +    def _get_connected_gloves(self):
Should be a static method or be outside the class

2022-08-10 09:20 UTC, bdenoun commented on src/polhemus_ros_driver/publish_static_knuckle_tf.py
> +class StaticKnuckleBroadcaster:
Does not need to be a class I would say, but that's a personal choice

2022-08-10 09:48 UTC, maxzieba commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        self.id = DataMarker._id = DataMarker._id + 1
every Marker needs to have a unique id, so I have a static class _id which increments with every instance and the value gets assigned to a newly created DataMarked. Happy to change it if there's a better way to do it

2022-08-10 09:56 UTC, maxzieba commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        if not self._hand_side == "lh":
Is there a difference? I prefer having not as its more visible/readable to me ( the ! blurs in sometimes )

2022-08-10 09:57 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        self.id = DataMarker._id = DataMarker._id + 1
Sorry I was not clear, could you add a comment explaining this line to help maintainability

2022-08-10 10:03 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        if not self._hand_side == "lh":
First, there can be a difference sometimes yes. There are no implied relationships among the comparison operators. The truth of x==y does not imply that x!=y is false since they call two different methods __eq__() and __neq()__.

Second, != is MUCH more readable and way more intuitive than the negation of a boolean, it's even part of the PEP recommendations.

Third, this can be super confusing for readers that are not super familiar with python and its priority rules. One could even read that (not x) == y. So that comes back to point 2, which does not improve readability.

2022-08-10 10:07 UTC, maxzieba commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        size_ratio = 0.2
We don't as otherwise the marker look really bad. That's the optimal value.

2022-08-10 10:11 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        size_ratio = 0.2
You might want the markers smaller or bigger depending on the resolution of the next generation of laptops right? ;)

2022-08-10 10:11 UTC, maxzieba commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        def _create_control(quaternion, name):
Local function for stronger encapsulation. Its only used by _create_marker to reduce the space used by the code to generate all the InteractiveMarkerControls.

2022-08-10 10:23 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_as.py
> +        def _create_control(quaternion, name):
I suppose you might want to do this if the nested function's definition varied each time for some reason, but that may indicate a flaw in your design. That said, there is a valid reason to do this to allow the nested function to use arguments that were passed to the outer function but not explicitly passed on to them, which sometimes occurs when writing function decorators, for example. 
But here there is absolutely no point in doing that (once again unadvised by PEP practices) except for the reason mentioned above. It makes the whole thing more difficult to read and to understand why this should be in this specific function.

2022-08-16 11:54 UTC, bdenoun approved these changes
Just change the two comments and I'm good with it

2022-08-16 11:54 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +            self._marker_server = InteractiveMarkerServer(f"knuckle_position_markers")
For this line (and the following) you don't need to make it an f-string

2022-08-16 11:54 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +colors = [Color.RED, Color.YELLOW, Color.BLUE, Color.GREEN]
This line and the two following are effectively constants, so please make them upper case.

2022-08-17 10:47 UTC, jeferrandiz98 approved these changes

2022-08-22 12:46 UTC, merged