Added documentation on method level
shadow-robot/polhemus_ros_driver pull request #40
Opened 2022-09-02 08:25 UTC by maxzieba

## Proposed changes

Added documentation on method level to new GUI for Polhemus glove calibration.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-09-05 14:05 UTC, jeferrandiz98 commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        """
Is this comment refered to this constructor?

2022-09-05 14:08 UTC, georgiablanco approved these changes

2022-09-05 14:14 UTC, jeferrandiz98 approved these changes

2022-09-05 14:41 UTC, beatrizleon requested changes

2022-09-05 14:41 UTC, beatrizleon commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        @param point1: Second point
Should it be like this?
```suggestion
        @param point1: First point
```

2022-09-05 14:41 UTC, beatrizleon commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        @param point1: Second point
Also maybe worth saying the format you are expecting points to be given

2022-09-05 14:41 UTC, beatrizleon commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        @param data: Input data
what should input data contain?

2022-09-05 14:41 UTC, beatrizleon commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +            @param name: Name of the marker definiding allowed motion inf format 'rotate/move_axis'
what does inf means?

2022-09-07 12:17 UTC, beatrizleon approved these changes

2022-09-07 12:18 UTC, merged