Fixing linter errors and adding license
shadow-robot/polhemus_ros_driver pull request #44
Opened 2022-10-03 12:00 UTC by jeferrandiz98

## Proposed changes

Fixing linter errors and adding license.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-10-04 10:51 UTC, toliver requested changes

2022-10-04 10:51 UTC, toliver commented on src/polhemus_ros_driver/source_pose_calibration.py
>  # Copyright (C) 2020 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
Missing 2022?

2022-11-01 09:52 UTC, rnzenha-s requested changes
Can you check whether the year "2018" should be kept for some of those licences?

2022-11-01 09:52 UTC, rnzenha-s commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        self.id = DataMarker._id = DataMarker._id + 1  # pylint: disable=C0103
Should we add "id" to the list of accepted variables? Otherwise maybe call it something like "marker_id"

2022-11-01 10:07 UTC, BenStarmerSmith commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        self.id = DataMarker._id = DataMarker._id + 1  # pylint: disable=C0103
I think id is an okay variable name, maybe we should add it

2022-11-07 09:28 UTC, toliver approved these changes

2022-11-07 09:28 UTC, rnzenha-s approved these changes

2022-11-07 09:28 UTC, merged