Improving calibration quality
shadow-robot/polhemus_ros_driver pull request #45
Opened 2023-02-14 16:20 UTC by georgiablanco

## Proposed changes

Improving calibration quality:
- New Sphere Fit algorithm from Scipy for calibration
- Using residuals for calibration quality 

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2023-02-20 08:20 UTC, jeferal commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +from __future__ import absolute_import, division
Should this be removed if using the new linter?

2023-02-20 08:34 UTC, jeferal commented on src/polhemus_ros_driver/sphere_fit.py
> +    sphere_fit = SphereFit(use_recorded_polhemus_data='/Ethan/2022-11-01-12-27-45.bag', plot=True)
I guess this should be removed, or implemented as unit test

2023-02-20 08:40 UTC, jeferal commented on src/polhemus_ros_driver/sphere_fit.py
> +                                           'rf': 'polhemus_station_3', 'lf': 'polhemus_station_4'}
In my opinion a class that is called SphereFit should be completely abstracted from polhemus. I think it shouldn't have any information related to polhemus. This class could also be used for any other sensor where a sphere fit is needed. In this case perhaps another class like PolhemusSphereFit could inherit from SphereFit and implement whatever it needs.

2023-02-20 08:41 UTC, jeferal commented on src/polhemus_ros_driver/sphere_fit.py
> +    def grid_vote(data, min_coords, max_coords, min_radius, max_radius, grid_points):
many of the following methods don't have documentation about the parameters and return

2023-02-22 11:08 UTC, jeferal commented on src/polhemus_ros_driver/sphere_fit.py
> +                                           'rf': 'polhemus_station_3', 'lf': 'polhemus_station_4'}
Marking as solved because after disussions this will be solved in a future refactor

2023-02-27 09:32 UTC, bdenoun requested changes

2023-02-27 09:32 UTC, bdenoun commented on launch/start.launch
> +  <arg name="z_hs" default="1" />
Could these parameter names be slighlthy more explicit? Especially the hs bit.

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +class Hand():
Don't need the brackets

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +class SrGloveCalibration():
same here

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        self._hands: "dict[str, Hand]" = {}
Not following our standard

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +    def _initialize_finger_data(self, hand: Hand):
not following standards

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +                        data_point_marker = DataMarker(hand.polhemus_base_name, Point(pos[0], pos[1], pos[2]),
```suggestion
                        data_point_marker = DataMarker(hand.polhemus_base_name, Point(*pos),
```

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +            return
Shouldn't this be a sys.exit() instead of a return?

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +    def _reset_data(hand: Hand):
Not following convention

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +            radius, center, residual = sphere_fit.fit_sphere([-0.1, -0.1, -0.1], [0.1, 0.1, 0.1], 0.03, 0.15)
Where do these parameters come from? If they have a meaning, they should be stored in constants with meaningful names

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/sphere_fit.py
> +                               bounds=(min_coords + [min_radius], max_coords + [max_radius]), f_scale=0.001)
Are you sure none of the parameters used here are worth parametrising?

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/sphere_fit.py
> +        print(arange)
Wanna keep teh print?

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/sphere_fit.py
> +        arange = []
I would strongly suggest renaming arange as this might be confusing since it's a method from numpy: https://numpy.org/doc/stable/reference/generated/numpy.arange.html

2023-02-27 09:32 UTC, bdenoun commented on src/polhemus_ros_driver/sphere_fit.py
> +        return sqrt((point_1.x - point_2.x) ** 2 + (point_1.y - point_2.y) ** 2 + (point_1.z - point_2.z) ** 2)
Why not simply using `np.linalg.norm(point_1 - point_2)`?

2023-03-06 14:19 UTC, ethanfowler commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +from __future__ import absolute_import, division
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:19 UTC, ethanfowler commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +from __future__ import absolute_import, division
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:19 UTC, ethanfowler commented on src/polhemus_ros_driver/sphere_fit.py
> +    sphere_fit = SphereFit(use_recorded_polhemus_data='/Ethan/2022-11-01-12-27-45.bag', plot=True)
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:20 UTC, ethanfowler commented on src/polhemus_ros_driver/sphere_fit.py
> +    def grid_vote(data, min_coords, max_coords, min_radius, max_radius, grid_points):
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:20 UTC, ethanfowler commented on launch/start.launch
> +  <arg name="z_hs" default="1" />
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:20 UTC, ethanfowler commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +class Hand():
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:20 UTC, ethanfowler commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +class SrGloveCalibration():
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:21 UTC, ethanfowler commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +        self._hands: "dict[str, Hand]" = {}
As since discussed, we need to reach a team consensus on this; we'll merge this pre-consensus as we're in a hurry.

2023-03-06 14:21 UTC, ethanfowler commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +    def _initialize_finger_data(self, hand: Hand):
As since discussed, we need to reach a team consensus on this; we'll merge this pre-consensus as we're in a hurry.

2023-03-06 14:22 UTC, ethanfowler commented on src/polhemus_ros_driver/knuckle_position_calibration_action_server.py
> +            radius, center, residual = sphere_fit.fit_sphere([-0.1, -0.1, -0.1], [0.1, 0.1, 0.1], 0.03, 0.15)
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:22 UTC, ethanfowler commented on src/polhemus_ros_driver/sphere_fit.py
> +                               bounds=(min_coords + [min_radius], max_coords + [max_radius]), f_scale=0.001)
Addressed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d

2023-03-06 14:22 UTC, ethanfowler commented on src/polhemus_ros_driver/sphere_fit.py
> +        print(arange)
Removed entirely, was better to use np.linspace than custom function.

2023-03-06 14:23 UTC, ethanfowler commented on src/polhemus_ros_driver/sphere_fit.py
> +        arange = []
Removed entirely (in https://github.com/shadow-robot/polhemus_ros_driver/commit/a4acc6bd34cb661ef38fb38cc47d0af0d90b5d4d), was better to use np.linspace than custom function.

2023-03-06 14:23 UTC, jeferal commented on test/test_sphere_fit.py
> +# import sys
why are these comments here?

2023-03-06 14:25 UTC, ethanfowler commented on src/polhemus_ros_driver/sphere_fit.py
> +        return sqrt((point_1.x - point_2.x) ** 2 + (point_1.y - point_2.y) ** 2 + (point_1.z - point_2.z) ** 2)
Done in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/88d0de77bee3abac466c91af5e8e27ea0b29b6bb

2023-03-06 14:25 UTC, ethanfowler commented on test/test_sphere_fit.py
> +# import sys
Whoops, fixed in https://github.com/shadow-robot/polhemus_ros_driver/pull/45/commits/0789c38159de32e27616222456218e9925d2b4bf

2023-03-06 14:57 UTC, jeferal approved these changes

2023-03-06 14:57 UTC, jeferal commented
Approved. For the checks there is just still a small linter error

2023-03-07 10:17 UTC, bdenoun approved these changes

2023-03-07 10:17 UTC, merged