Allowing fewer sensors
shadow-robot/polhemus_ros_driver pull request #55
Opened 2023-06-07 09:52 UTC by jeferal

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropriate.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2023-06-21 16:06 UTC, bdenoun commented on include/polhemus_ros_driver/liberty.hpp
> +            int sensors_right_glove, int sensors_left_glove);
Do you really need an int? Can't this be an uint8?

2023-06-21 16:06 UTC, bdenoun commented on include/polhemus_ros_driver/polhemus.hpp
> +           int sensors_right_glove, int sensors_left_glove);
Same question here

2023-06-21 16:07 UTC, bdenoun commented on src/polhemus_ros_driver/polhemus.cpp
> +                   int sensors_right_glove, int sensors_left_glove):
same here?

2023-06-22 08:03 UTC, bdenoun commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
> +  int i, nstations, sensors_right_glove, sensors_left_glove;
could we have `i` and `nstations` more meaningful?

2023-06-26 08:25 UTC, jeferal commented on include/polhemus_ros_driver/liberty.hpp
> +            int sensors_right_glove, int sensors_left_glove);
No, I don't really need it, thank you. I changed it in [ec70607](https://github.com/shadow-robot/polhemus_ros_driver/pull/55/commits/ec70607d039a8f69adcf42ab505f5fcef7b2ee86)

2023-06-26 08:25 UTC, jeferal commented on include/polhemus_ros_driver/polhemus.hpp
> +           int sensors_right_glove, int sensors_left_glove);
[ec70607](https://github.com/shadow-robot/polhemus_ros_driver/pull/55/commits/ec70607d039a8f69adcf42ab505f5fcef7b2ee86)

2023-06-26 08:26 UTC, jeferal commented on src/polhemus_ros_driver/polhemus.cpp
> +                   int sensors_right_glove, int sensors_left_glove):
[ec70607](https://github.com/shadow-robot/polhemus_ros_driver/pull/55/commits/ec70607d039a8f69adcf42ab505f5fcef7b2ee86)

2023-06-26 08:43 UTC, georgiablanco approved these changes

2023-06-26 08:43 UTC, jeferal commented on src/polhemus_ros_driver/polhemus_tf_broadcaster.cpp
> +  int i, nstations, sensors_right_glove, sensors_left_glove;
Changed in [de26999](https://github.com/shadow-robot/polhemus_ros_driver/pull/55/commits/de269994fae3ac810d263dca8e5336b9cbfc67ea)

2023-06-26 08:49 UTC, bdenoun requested changes

2023-06-26 08:49 UTC, bdenoun commented on src/polhemus_ros_driver/viper.cpp
>    int retval = RETURN_ERROR;
```suggestion
  int return_value = RETURN_ERROR;
```

2023-06-26 08:49 UTC, bdenoun commented on src/polhemus_ros_driver/viper.cpp
> +  retval = set_device_to_receive_saved_calibration();
```suggestion
  return_value = set_device_to_receive_saved_calibration();
```

2023-06-26 08:49 UTC, bdenoun commented on src/polhemus_ros_driver/viper.cpp
>    if (RETURN_ERROR == retval)
```suggestion
  if (RETURN_ERROR == return_value)
```

2023-06-26 08:49 UTC, bdenoun commented on src/polhemus_ros_driver/viper.cpp
>    if (RETURN_ERROR == retval)
Might have missed some

2023-06-28 09:17 UTC, jeferal commented
I changed the retval variable name for return_value in [d3662e4](https://github.com/shadow-robot/polhemus_ros_driver/pull/55/commits/d3662e401196eb1458bb59ea6c35af6e8a6d4610). Just in case, because of the last small changes, I tested the driver works by teleoperating unimanual and bimanual

2023-06-28 09:21 UTC, bdenoun approved these changes

2023-06-28 14:18 UTC, merged